name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: matrix.os
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          KEY: ${{ secrets.KEY }}
        run: |
          ssh git@github.com:Zhidkov-Aleksandr/Calculator.git "cd /path/to/your/app && git pull && mvn clean install && java -jar target/calculator.jar"
